#!/usr/bin/env python

print '\n'
print 'Commands available to interact with AWS:'
print ''
print '* awsls'
print '\tList volumes and instances. Include "-c" to list STARclusters'
print ''
print '* awskill'
print '\tTerminate instance or cluster'
print ''
print '* awslaunch'
print '\tBoot up instance'
print ''
print '* awslaunch_cluster'
print '\tBoot up cluster of instances using STARcluster'
print ''
print '* aws_spot_price_history'
print '\tList spot price for a given instance and availability zone'
print ''
print '* aws_ebs_create'
print '\tCreate EBS volume'
print ''
print '* aws_ebs_delete'
print '\tDelete EBS volume'
print ''
print '* aws_ebs_attach'
print '\tAttach EBS volume to running instance'
print ''
print '* aws_ebs_detach'
print '\tDetach EBS volume from instance'

print '\n'
