#!/usr/bin/env python
import subprocess
import os
import sys 

if len(sys.argv) != 2: 
	print '\nPlease provide project description in "double quotes"\n'
	sys.exit()

cwd=os.getcwd()

cwd=cwd.split('/')[-1]	
cwd=cwd.split('_')
cwd='-'.join(cwd)
cwd=cwd.lower()

if os.path.exists('.aws_relion_project_info'): 
	print 'Error: project information file .aws_relion_project_info already exists. Exiting'
	sys.exit()

o1=open('.aws_relion_project_info','w')
o1.write('project_name=%s\n' %(cwd))
o1.write('description=%s\n' %(sys.argv[1]))
o1.close()

#Place onto s3 bucket: rln-aws-{team}-{keyname}/aws_relion_project_info
keypair=subprocess.Popen('echo $KEYPAIR_PATH',shell=True, stdout=subprocess.PIPE).stdout.read().strip()
teamname=subprocess.Popen('echo $RESEARCH_GROUP_NAME',shell=True, stdout=subprocess.PIPE).stdout.read().strip()
keyname=keypair.split('/')[-1].split('.pem')[0]
keyname=keyname.split('_')
keyname='-'.join(keyname)

bucketname='rln-aws-%s-%s' %(teamname,keyname)

#Check if it exists:
try: 
	cmd='aws s3 ls %s' %(bucketname)
	result=subprocess.check_output(cmd,stderr=subprocess.STDOUT,shell=True)
	s3exists=True
except: 
	s3exists=False

#Create bucket if doesn't exist
if s3exists is False: 
	cmd='aws s3 mb s3://%s' %(bucketname)	
	subprocess.Popen(cmd,shell=True).wait()

#Check if project file exists
if os.path.exists('s3tmpout.txt'):
	os.remove('s3tmpout.txt')
cmd='aws s3 ls %s/aws_relion_project_info.txt > s3tmpout.txt' %(bucketname)
subprocess.Popen(cmd,shell=True).wait()

numlines=len(open('s3tmpout.txt','r').readlines())
if numlines > 0: 
	infoexists=True
if numlines == 0: 
	infoexists=False
os.remove('s3tmpout.txt')

if infoexists is True: 
	if os.path.exists('tmpinfofile222.txt'):
                os.remove('tmpinfofile222.txt')
	cmd='aws s3 cp s3://%s/aws_relion_project_info.txt tmpinfofile222.txt > s3tmpout.txt' %(bucketname)
	subprocess.Popen(cmd,shell=True).wait()

	#Check if project name already exists: 
	o11=open('tmpinfofile222.txt','r')
	for line in o11: 
		if line.split()[0] == cwd: 
			print '\nError: Project name %s already exists. Please change the name of project directory "%s" and try again\n' %(cwd,cwd)
			os.remove('.aws_relion_project_info')
			sys.exit()
	o11.close()

	cmd='aws s3 rm s3://%s/aws_relion_project_info.txt > s3tmpout.txt' %(bucketname)
        subprocess.Popen(cmd,shell=True).wait()

cmd='echo "%s\t\t%s" >> tmpinfofile222.txt' %(cwd,sys.argv[1])
subprocess.Popen(cmd,shell=True).wait()

cmd='aws s3 cp tmpinfofile222.txt s3://%s/aws_relion_project_info.txt > s3tmpout.txt' %(bucketname)
subprocess.Popen(cmd,shell=True).wait()

print '\nInitialization complete for project: %s\n' %(cwd)

if os.path.exists('s3tmpout.txt'): 
	os.remove('s3tmpout.txt')
if os.path.exists('tmpinfofile222.txt'): 
	os.remove('tmpinfofile222.txt')

