#!/usr/bin/env python
import os
import sys
import subprocess

if len(sys.argv) != 2: 
	print "\nPlease provide directory name to delete\n"
	sys.exit()

def query_yes_no(question, default="no"):
        valid = {"yes": True, "y": True, "ye": True,"no": False, "n": False}
        if default is None:
                prompt = " [y/n] "
        elif default == "yes":
                prompt = " [Y/n] "
        elif default == "no":
                prompt = " [y/N] "
        else:
                raise ValueError("invalid default answer: '%s'" % default)
        while True:
                sys.stdout.write(question + prompt)
                choice = raw_input().lower()
                if default is not None and choice == '':
                        return valid[default]
                elif choice in valid:
                        return valid[choice]
                else:
                        sys.stdout.write("Please respond with 'yes' or 'no' "
                                         "(or 'y' or 'n').\n")

keypair=subprocess.Popen('echo $KEYPAIR_PATH',shell=True, stdout=subprocess.PIPE).stdout.read().strip()
teamname=subprocess.Popen('echo $RESEARCH_GROUP_NAME',shell=True, stdout=subprocess.PIPE).stdout.read().strip()
keyname=keypair.split('/')[-1].split('.pem')[0]
keyname=keyname.split('_')
keyname='-'.join(keyname)

bucketname='rln-aws-%s-%s' %(teamname,keyname)

projectname=sys.argv[1]

answer=query_yes_no("\nAre you sure that you want to delete directory %s? This cannot be undone." %(projectname))

if answer is True:

	#Remove line from project text file
	if os.path.exists('s3tmpout.txt'): 
		os.remove('s3tmpout.txt')

	if projectname[-1] == '/': 
		projectname=projectname[:-1]

	cmd='aws s3 rm s3://%s/%s/ --recursive > s3tmpout.txt' %(bucketname,projectname)
	subprocess.Popen(cmd,shell=True).wait()

	if os.path.exists('s3tmpout.txt'): 
		os.remove('s3tmpout.txt')


	print ''
	print 'Success!'
