#!/usr/bin/env python
import os
import subprocess
import sys 

listall=True
if len(sys.argv) == 2: 
	listall=False
	projectname=sys.argv[1]

#List all s3 buckets with the name: rln-aws-{team}-{keyname} and that don't have more than 5 entries when split by '-'
keypair=subprocess.Popen('echo $KEYPAIR_PATH',shell=True, stdout=subprocess.PIPE).stdout.read().strip()
teamname=subprocess.Popen('echo $RESEARCH_GROUP_NAME',shell=True, stdout=subprocess.PIPE).stdout.read().strip()
keyname=keypair.split('/')[-1].split('.pem')[0]
keyname=keyname.split('_')
keyname='-'.join(keyname)
keyname=keyname.lower()

basename='rln-aws-%s-%s' %(teamname,keyname)
basename=basename.lower()

if listall is True: 
	print '\nProjects on AWS for user %s:' %(keypair.split('/')[-1].split('.pem')[0])
	print '\nProject name\t\t\tDescription'
	print '-----------------------------------------------'
	if os.path.exists('s3tmplist.txt'): 
		os.remove('s3tmplist.txt')


	#Check if it exists:
	try:
        	cmd='aws s3 ls %s' %(basename)
        	result=subprocess.check_output(cmd,stderr=subprocess.STDOUT,shell=True)
        	s3exists=True
	except:
        	s3exists=False

	if s3exists is False: 
		print 'No projects found\n'
		if os.path.exists('tmpinfofile222.txt'): 
	                os.remove('tmpinfofile222.txt')
                if os.path.exists('s3tmpout.txt'):
        	        os.remove('s3tmpout.txt')
		sys.exit()

	if s3exists is True: 
		#Check if project file exists
		if os.path.exists('s3tmpout.txt'):
        		os.remove('s3tmpout.txt')
		cmd='aws s3 ls %s/aws_relion_project_info.txt > s3tmpout.txt' %(basename)
		subprocess.Popen(cmd,shell=True).wait()

		numlines=len(open('s3tmpout.txt','r').readlines())
		if numlines > 0:
		        infoexists=True
		if numlines == 0:
		        infoexists=False
		os.remove('s3tmpout.txt')

		if infoexists is False:
			if os.path.exists('tmpinfofile222.txt'): 
				os.remove('tmpinfofile222.txt')
			if os.path.exists('s3tmpout.txt'): 
				os.remove('s3tmpout.txt')
			print 'No projects found\n'
			sys.exit()
		if infoexists is True:
		        if os.path.exists('tmpinfofile222.txt'):
		                os.remove('tmpinfofile222.txt')
		        cmd='aws s3 cp s3://%s/aws_relion_project_info.txt tmpinfofile222.txt > s3tmpout.txt' %(basename)
		        subprocess.Popen(cmd,shell=True).wait()
			o1=open('tmpinfofile222.txt','r')
			for line in o1: 
				print line.strip()
			o1.close()
			if os.path.exists('tmpinfofile222.txt'): 
                                os.remove('tmpinfofile222.txt')
                        if os.path.exists('s3tmpout.txt'):
                                os.remove('s3tmpout.txt')	

		print '\n'
	'''
	
	cmd='aws s3 ls > s3tmplist.txt'
	subprocess.Popen(cmd,shell=True).wait()

	#Goal: print out all directories that do not have subdirectories
	counter=0
	projectlist=[]
	for line in open('s3tmplist.txt','r'): 
		if len(line.split(basename)) > 1: 
			line=line.split()[-1]
			if len(line.split(keyname)) == 2: 
				if len(line.split(keyname)[-1]) > 0: 
					projectlist.append(line)
					#print line 
					counter=counter+1

	donelist=[]
	for project in projectlist: 
		flag=0
		print 'project:%s' %(project)
		for sub in projectlist: 
			if sub not in donelist: 
				print 'sub:%s %i' %(sub,len(project.split(sub)))
				if len(project.split(sub)[-1]) > 0:
					print sub
				donelist.append(sub)
		if flag==1: 
			print 'select: %s' %project
	if counter == 0: 
		print 'No projects found'

	os.remove('s3tmplist.txt')
	print '\n'
	'''
if listall is False: 

	if projectname[-1] == '/': 
		projectname=projectname[:-1]
	basename=basename+'/'+projectname+'/'

	print '\nSubdirectories & files in project %s for user %s:' %(projectname,keypair.split('/')[-1].split('.pem')[0])
	print '-----------------------------------------------'
        if os.path.exists('s3tmplist.txt'):
                os.remove('s3tmplist.txt')

        cmd='aws s3 ls %s > s3tmplist.txt' %(basename)
	subprocess.Popen(cmd,shell=True).wait()

        counter=0
	for line in open('s3tmplist.txt','r'):
        	print line.split()[-1]
                counter=counter+1
        if counter == 0:
                print 'No projects found'

        os.remove('s3tmplist.txt')
        print '\n'

